define:
  paging:
    defaultSize: 15
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.99:8761/eureka/
spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 192.168.3.30
          brokers: 192.168.3.30
  zipkin:
    enabled: false
    base-url: http://192.168.3.30:9411
  sleuth:
    sampler:
      percentage: 0.1
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
logging:
  level:
    com.qianjh.microservice: debug
  file: D:\Logs\com\qianjh\microservices\${spring.application.name}.log